services:
  trace_scraper:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: trace_scraper
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: trace_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
